import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const areas=[['Civil','Contratos, deudas, propiedad y responsabilidad'],['Penal','Delitos, denuncias y conceptos penales'],['Laboral','Contrato, despido, remuneraciones y derechos'],['Consumidor','Compras, garantías, cobros y servicios'],['Comercial','Empresas, actos de comercio y sociedades'],['Familia','Alimentos, cuidado personal y relaciones familiares'],['Vivienda','Arriendo, copropiedad y restitución'],['Datos','Privacidad y protección de datos']];
const sources=[
 ['Código Civil','BCN / LeyChile','https://www.bcn.cl/leychile/navegar?idNorma=1973'],
 ['Código Penal','BCN / LeyChile','https://www.bcn.cl/leychile/navegar?idNorma=1984'],
 ['Código de Comercio','BCN / LeyChile','https://www.bcn.cl/leychile/navegar?idNorma=1974'],
 ['Código del Trabajo','BCN / LeyChile','https://www.bcn.cl/leychile/navegar?idNorma=207436'],
 ['Código de Procedimiento Civil','Corpus planificado',''],['Código Procesal Penal','Corpus planificado',''],['Código Orgánico de Tribunales','Corpus planificado',''],
 ['Ley de Consumidor 19.496','Corpus planificado',''],['Insolvencia 20.720','Corpus planificado',''],['Copropiedad 21.442','Corpus planificado',''],['Arrendamiento 18.101','Corpus planificado',''],['Tribunales de Familia 19.968','Corpus planificado',''],['Responsabilidad penal PJ 20.393','Corpus planificado',''],['Delitos Económicos 21.595','Corpus planificado',''],['Protección de datos','Corpus versionado planificado','']
];
function orient(q){let t=q.toLowerCase(),a=t.match(/despid|trabaj|sueldo|finiquito/)?'Laboral':t.match(/delit|robo|estafa|denuncia|fiscal/)?'Penal':t.match(/compra|garant|sernac|producto/)?'Consumidor':t.match(/arriendo|arrend|departamento|gasto común/)?'Vivienda':t.match(/empresa|sociedad|comerc/)?'Comercial':'Civil';return {a,text:`Tu relato parece corresponder principalmente al área ${a}. En esta versión inicial puedo ordenar el problema y mostrarte qué información jurídica debería verificarse, pero no voy a inventar artículos ni plazos. Antes de tomar una decisión debe contrastarse el caso con la legislación vigente y, cuando corresponda, con un abogado.`,steps:['Guarda contratos, mensajes, cartas, comprobantes y fechas relevantes.','Identifica cuándo ocurrió cada hecho y quiénes participaron.','No dejes pasar una notificación o plazo formal sin revisión profesional.','Verifica la norma vigente y los artículos aplicables antes de actuar.']}}
function App(){const[q,setQ]=useState(''),[r,setR]=useState(null),[dark,setDark]=useState(false),[tab,setTab]=useState('chat');const count=useMemo(()=>sources.length,[]);return <main className={dark?'dark':''}><nav><b><span>Abog</span><i>AI</i></b><div><button onClick={()=>setTab('chat')}>Orientación</button><button onClick={()=>setTab('base')}>Base jurídica</button><button onClick={()=>setDark(!dark)}>{dark?'Día':'Noche'}</button></div></nav>{tab==='chat'?<><section className="hero"><div className="pill">Orientación jurídica · Chile</div><h1>Entiende tu situación<br/><em>antes de decidir.</em></h1><p>Describe lo que ocurrió. AbogAI organiza los hechos, identifica el área legal y te ayuda a preparar una consulta informada.</p></section><section className="chat"><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Cuéntame qué ocurrió, incluyendo fechas si las conoces…"/><div className="bar"><small>No incluyas datos personales innecesarios.</small><button className="primary" disabled={!q.trim()} onClick={()=>setR(orient(q))}>Analizar situación →</button></div></section><div className="chips">{areas.slice(0,5).map(x=><button key={x[0]} onClick={()=>setQ(`Necesito orientación sobre un problema de ${x[0].toLowerCase()}. `)}>{x[0]}</button>)}</div>{r&&<section className="answer"><div className="eyebrow">ORIENTACIÓN PRELIMINAR · {r.a.toUpperCase()}</div><h2>Qué significa</h2><p>{r.text}</p><h3>Qué conviene hacer ahora</h3><ol>{r.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="warning"><b>Importante</b><br/>Esta orientación es informativa. No reemplaza asesoría jurídica profesional ni constituye una conclusión sobre el resultado de un caso.</div><button onClick={()=>window.print()}>Generar resumen para abogado</button></section>}</>:<section className="library"><div className="pill">Corpus jurídico v0.1</div><h1>Base de conocimiento</h1><p>{count} cuerpos normativos y módulos definidos. Las fuentes oficiales se versionarán por vigencia, artículo e inciso.</p><div className="grid">{sources.map(s=><article key={s[0]}><span>{s[1]}</span><h3>{s[0]}</h3>{s[2]?<a href={s[2]} target="_blank">Fuente oficial ↗</a>:<small>Integración pendiente</small>}</article>)}</div></section>}<footer>AbogAI · Orientación jurídica asistida por IA · No sustituye a un abogado</footer></main>};createRoot(document.getElementById('root')).render(<App/>);